chore: Adjust vue components to type correctly
numberscope/frontscope pull request #136
Opened 2022-07-07 16:32 UTC by gwhitney

This PR modifies the node `dev` and `build` scripts and the pre-commit
  actions to typecheck all code in Vue components. Correspondingly, it
  adjusts all of the components to pass TypeScript type checking. In particular,
  this means boilerplate of a call to Vue.defineComponent() in every component
  and view (per Vue 3 documentation; otherwise TypeScript cannot infer the
  proper types).

  The most significant resulting change was to the mechanism of generating
  unique canvas ids in BundleCard, as the previous mechanism did not allow
  defineComponent() to infer the type of the `cid` member. This commit
  therefore switches to a later proposed mechanism in the same Vue GitHub issue
  referenced by the comment on the previous mechanism.

  One other change worth mentioning is that in several places data properties
  called "id" or "uid" were being used as `v-bind:key` values, from objects
  that had no such properties. These have all been changed to use "name"
  properties, which do exist. That leads to the question of whether there will
  be a problem if two Sequences (say) have the same "name". It seems unlikely,
  since presumably before this change, the "id" properties were all undefined
  and hence identical.

  Otherwise, the changes were essentially all type annotation. Note that there
  was a great deal of new annotation in SeqVizParamsModal as the Paramable
  interface is currently based on a (probably not particularly
  TypeScript-conformant) scheme of string properties determining what type
  an "unknown" value should be cast to. In particular, some of this typecasting
  unfortunately as far as I could figure out has to happen in `v-model`
  directives, forcing me to turn off the `vue/valid-v-model` eslint rule (as
  `value as boolean`, for example, does not qualify as an l-value in eslint's
  judgment).

  Resolves #131.

2022-07-10 21:56 UTC, liam-mulhall requested changes
* I pulled the changes, ran `npm run typecheck`, and I'm not getting any errors! :)
* No errors from `npm run dev`, as expected.
* No errors from `npm run build`, as expected.

# Manual Testing

When I go to the scope, I get the following warnings in the browser console (right click on browser window > Inspect) on both Safari, Chrome, and Firefox:

```
[Warning] [Vue warn]: Invalid prop: type check failed for prop "activeViz". Expected Object, got Null  (20) (chunk-YKE26KAB.js, line 1262)
"
"
" at <BundleManager"
"activeViz=null"
"activeSeq="
SequenceRandom
"bundles="
Array (3)
" ..."
">"
"
"
" at <ToolMain"
"onVnodeUnmounted=fn<onVnodeUnmounted>"
"ref=Ref<"
Proxy
">"
">"
"
"
" at <RouterView>"
"
"
" at <App>"
```

```
[Warning] [Vue warn]: Invalid prop: type check failed for prop "activeSeq". Expected Object, got Null  (19) (chunk-YKE26KAB.js, line 1262)
"
"
" at <BundleManager"
"activeViz=null"
"activeSeq=null"
"bundles="
Array (3)
" ..."
">"
"
"
" at <ToolMain"
"onVnodeUnmounted=fn<onVnodeUnmounted>"
"ref=Ref<"
Proxy
">"
">"
"
"
" at <RouterView>"
"
"
" at <App>"
```

I think going forward we want to avoid logs, warnings, and errors in the browser console.

2022-07-10 21:56 UTC, liam-mulhall commented on src/views/About.vue
> +    import {defineComponent} from 'vue'
@gwhitney, could you explain this? I don't understand what's going on here.

2022-07-10 22:02 UTC, liam-mulhall commented on src/views/About.vue
> +    import {defineComponent} from 'vue'
See https://vuejs.org/guide/typescript/overview.html#definecomponent.

2022-07-11 00:20 UTC, gwhitney commented
I agree, there should not be any warnings or errors in the browser console. I will investigate and push a commit to fix this. Marking as draft in the meantime.

2022-07-11 15:48 UTC, gwhitney commented
OK, didn't realize I had to tell both Vue and TypeScript that null was a possible value for two props of the BundleManager (sadly, there is definitely redundancy between the Vue spec and the TypeScript typing).

2022-07-11 16:06 UTC, liam-mulhall approved these changes
I looked the file over and checked the console in Chrome, Firefox, and Safari. Looks good!

2022-07-11 16:06 UTC, merged